import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "NickGen Terms of Service. Read the terms and conditions for using our free nickname generator service.",
};

const TermsPage = () => {
  return (
    <div className="px-4 sm:px-6 lg:px-8 py-12 md:py-20">
      <div className="max-w-4xl mx-auto">
        <article className="card-glow rounded-2xl p-8 md:p-12">
          <h1 className="text-3xl md:text-4xl font-bold text-white mb-8">
            Terms of Service
          </h1>

          <div className="prose prose-invert prose-slate max-w-none">
            <p className="text-slate-300 mb-6">
              Last updated: January 2026
            </p>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">
              1. Acceptance of Terms
            </h2>
            <p className="text-slate-300 mb-4">
              By accessing and using NickGen, you accept and agree to be bound
              by these Terms of Service. If you do not agree to these terms,
              please do not use our service.
            </p>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">
              2. Description of Service
            </h2>
            <p className="text-slate-300 mb-4">
              NickGen provides a free online nickname generator for gaming and
              other purposes. Our service generates random nickname suggestions
              based on predefined patterns and word combinations. The service is
              provided as-is without any guarantees.
            </p>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">
              3. Use of Generated Nicknames
            </h2>
            <p className="text-slate-300 mb-4">
              Nicknames generated by our service are provided for suggestion
              purposes only. You are free to use any generated nickname for your
              personal gaming accounts or other purposes. However, please note:
            </p>
            <ul className="text-slate-300 space-y-2 mb-4">
              <li>
                We do not guarantee that any nickname will be available on
                gaming platforms or other services.
              </li>
              <li>
                We do not claim ownership over generated nicknames, and multiple
                users may receive the same suggestions.
              </li>
              <li>
                You are responsible for ensuring that your chosen nickname
                complies with the terms of service of the platforms where you
                use it.
              </li>
            </ul>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">
              4. Content Filtering
            </h2>
            <p className="text-slate-300 mb-4">
              We implement automated filtering to prevent the generation of
              inappropriate, offensive, or harmful nicknames. While we strive to
              filter all such content, no filtering system is perfect. If you
              encounter an inappropriate nickname, we appreciate your
              understanding that it was not intentional.
            </p>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">
              5. Prohibited Uses
            </h2>
            <p className="text-slate-300 mb-4">
              You agree not to use NickGen for:
            </p>
            <ul className="text-slate-300 space-y-2 mb-4">
              <li>Any illegal or unauthorized purpose</li>
              <li>
                Attempting to bypass or circumvent our content filtering systems
              </li>
              <li>
                Automated scraping or mass generation for commercial purposes
              </li>
              <li>
                Any activity that could harm, disable, or impair our service
              </li>
            </ul>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">
              6. Intellectual Property
            </h2>
            <p className="text-slate-300 mb-4">
              The NickGen website, including its design, code, and branding, is
              protected by intellectual property laws. You may not copy,
              reproduce, or distribute any part of our website without
              permission. The word combinations used in our generator are
              compiled from common words and are not proprietary.
            </p>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">
              7. Advertisements
            </h2>
            <p className="text-slate-300 mb-4">
              NickGen displays advertisements to support our free service. By
              using our service, you agree to the display of advertisements.
              Advertisement content is provided by third-party networks and we
              are not responsible for their content.
            </p>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">
              8. Disclaimer of Warranties
            </h2>
            <p className="text-slate-300 mb-4">
              NickGen is provided as-is and as-available without warranties of
              any kind, express or implied. We do not guarantee that the service
              will be uninterrupted, secure, or error-free. We make no warranty
              regarding the quality, accuracy, or reliability of the service.
            </p>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">
              9. Limitation of Liability
            </h2>
            <p className="text-slate-300 mb-4">
              To the fullest extent permitted by law, NickGen shall not be
              liable for any indirect, incidental, special, consequential, or
              punitive damages arising from your use of the service, including
              but not limited to loss of profits, data, or other intangible
              losses.
            </p>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">
              10. Changes to Terms
            </h2>
            <p className="text-slate-300 mb-4">
              We reserve the right to modify these terms at any time. Changes
              will be effective immediately upon posting to this page. Your
              continued use of the service after changes constitutes acceptance
              of the modified terms.
            </p>

            <h2 className="text-xl font-semibold text-white mt-8 mb-4">
              11. Contact
            </h2>
            <p className="text-slate-300">
              If you have any questions about these Terms of Service, please
              contact us through our About page.
            </p>
          </div>
        </article>
      </div>
    </div>
  );
};

export default TermsPage;
